# Generated by Django 4.2.21 on 2025-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Überschrift / Name des Contents', max_length=200)),
                ('body', models.TextField(blank=True, help_text='Text oder Beschreibung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('ad_account_id', models.CharField(blank=True, help_text='Meta Ad Account ID', max_length=50, null=True)),
                ('objective', models.CharField(blank=True, help_text='Ad-Objective, z.B. LINK_CLICKS', max_length=50, null=True)),
                ('daily_budget', models.PositiveIntegerField(blank=True, help_text='Budget pro Tag in Cent', null=True)),
                ('spend_cap', models.PositiveIntegerField(blank=True, help_text='Max. Gesamtausgaben in Cent', null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Anzeigen-Startzeit (Ads)', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Anzeigen-Endzeit (Ads)', null=True)),
                ('attribution_spec', models.JSONField(blank=True, help_text='Attribution-Spezifikation als JSON-Liste', null=True)),
            ],
        ),
    ]
