# Generated by Django 4.2.21 on 2025-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_alter_keyword_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('monthly_searches', models.IntegerField(null=True)),
                ('competition', models.CharField(max_length=10, null=True)),
                ('low_cpc', models.FloatField(null=True)),
                ('high_cpc', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
