# Generated by Django 4.2.21 on 2025-07-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('facebook', 'Facebook (organisch)'), ('instagram', 'Instagram (organisch)'), ('facebook_ads', 'Facebook Ads'), ('email', 'E-Mail')], help_text='Ziel-Channel, z.B. facebook_ads', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='Datum & Uhrzeit der Ausspielung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen')], default='pending', help_text='Status: pending, sent oder failed', max_length=10)),
                ('content', models.ForeignKey(help_text='Verknüpft das Content-Objekt', on_delete=django.db.models.deletion.CASCADE, to='content.content')),
            ],
        ),
    ]
