# Generated by Django 4.2.21 on 2025-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoaudit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='seoaudit',
            old_name='audit_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='h1_count',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='h2_count',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='h3_count',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='load_time_ms',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='seoaudit',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='load_time',
            field=models.IntegerField(default=0, help_text='Ladezeit in Millisekunden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='broken_links',
            field=models.IntegerField(),
        ),
    ]
