# Generated by Django 4.2.21 on 2025-05-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_remove_seoaudit_h1_count_remove_seoaudit_h2_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seoaudit',
            old_name='title',
            new_name='meta_title',
        ),
    ]
