# Generated by Django 4.2.21 on 2025-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_seoaudit_h1_count_seoaudit_h2_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoaudit',
            name='canonical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
