# Generated by Django 4.2.21 on 2025-05-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0010_seoaudit_http_status_seoaudit_robots_txt_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoaudit',
            name='robots_txt_found',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='sitemap_found',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
