# Generated by Django 4.2.21 on 2025-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0011_alter_seoaudit_robots_txt_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='cls',
            field=models.FloatField(blank=True, help_text='Cumulative Layout Shift', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='fcp',
            field=models.FloatField(blank=True, help_text='First Contentful Paint in ms', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='lcp',
            field=models.FloatField(blank=True, help_text='Largest Contentful Paint in ms', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='tti',
            field=models.FloatField(blank=True, help_text='Time To Interactive in ms', null=True),
        ),
    ]
