# Generated by Django 4.2.21 on 2025-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0015_seoaudit_robots_directives_seoaudit_sitemap_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='js_render_blocking_resources',
            field=models.TextField(blank=True, help_text='Liste der clientseitig geladenen JavaScript-Ressourcen', null=True),
        ),
    ]
