# Generated by Django 4.2.21 on 2025-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0016_seoaudit_js_render_blocking_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='title_keyword_position',
            field=models.IntegerField(blank=True, help_text='1-basierte Position des primären Keywords im Title, 0 wenn nicht gefunden', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='title_length',
            field=models.IntegerField(blank=True, help_text='Länge des <title>-Tags in Zeichen', null=True),
        ),
    ]
