# Generated by Django 4.2.21 on 2025-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0017_seoaudit_title_keyword_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='meta_description_length',
            field=models.IntegerField(blank=True, help_text='Länge der Meta-Description in Zeichen', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='meta_description_unique',
            field=models.BooleanField(blank=True, default=True, help_text='True, wenn Meta-Description nicht in älteren Audits vorhanden', null=True),
        ),
    ]
