# Generated by Django 4.2.21 on 2025-06-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0019_seoaudit_h3_count_seoaudit_h4_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='keyword_density',
            field=models.FloatField(blank=True, help_text='Keyword-Dichte in Prozent (Anteil Keyword/Wortanzahl)', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='reading_score',
            field=models.FloatField(blank=True, help_text='Flesch-Reading-Ease Score', null=True),
        ),
    ]
