# Generated by Django 4.2.21 on 2025-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0020_seoaudit_keyword_density_seoaudit_reading_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='duplicate_sections',
            field=models.TextField(blank=True, help_text='Wiederholt vorkommende Sätze oder Absätze', null=True),
        ),
    ]
