# Generated by Django 4.2.21 on 2025-06-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0021_seoaudit_duplicate_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='backlink_count',
            field=models.IntegerField(blank=True, help_text='Geschätzte Gesamtzahl der Backlinks (externe Links)', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='referring_domains',
            field=models.IntegerField(blank=True, help_text='Anzahl der einzigartigen Domains, die verlinken', null=True),
        ),
    ]
