# Generated by Django 4.2.21 on 2025-05-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('title_tag', models.CharField(blank=True, max_length=512)),
                ('meta_description', models.CharField(blank=True, max_length=1024)),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('h3_count', models.IntegerField(default=0)),
                ('load_time_ms', models.IntegerField(blank=True, null=True)),
                ('broken_links', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='websites.website')),
            ],
        ),
    ]
