# Generated by Django 4.2.21 on 2025-05-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('seo', '0002_alter_seoaudit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoaudit',
            options={},
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='broken_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='load_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website'),
        ),
    ]
