# Generated by Django 4.2.21 on 2025-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_seoaudit_options_alter_seoaudit_broken_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='canonical',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='h1_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='h2_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='meta_robots',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='meta_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='og_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='broken_links',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='load_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='score',
            field=models.IntegerField(),
        ),
    ]
