# Generated by Django 4.2.21 on 2025-05-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_alter_seoaudit_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoaudit',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='meta_hreflang',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='meta_robots',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='twitter_card',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seoaudit',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
