# Generated by Django 4.2.21 on 2025-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0012_seoaudit_cls_seoaudit_fcp_seoaudit_lcp_seoaudit_tti'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='redirect_chain_length',
            field=models.IntegerField(blank=True, help_text='Anzahl der Redirects bis zum finalen Ziel', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='redirect_loop',
            field=models.BooleanField(blank=True, default=False, help_text='True, wenn eine Redirect-Schleife erkannt wurde', null=True),
        ),
    ]
