# Generated by Django 4.2.21 on 2025-05-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0013_seoaudit_redirect_chain_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='cipher_strength',
            field=models.CharField(blank=True, help_text='Cipher-Stärke des SSL/TLS-Zertifikats', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='csp',
            field=models.BooleanField(blank=True, default=False, help_text='Content-Security-Policy-Header vorhanden', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='hsts',
            field=models.BooleanField(blank=True, default=False, help_text='Strict-Transport-Security-Header vorhanden', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='ssl_valid_until',
            field=models.DateTimeField(blank=True, help_text='Gültigkeitsende des SSL/TLS-Zertifikats', null=True),
        ),
    ]
