# Generated by Django 4.2.21 on 2025-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0014_seoaudit_cipher_strength_seoaudit_csp_seoaudit_hsts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='robots_directives',
            field=models.TextField(blank=True, help_text='Gefundene Direktiven aus robots.txt', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='sitemap_errors',
            field=models.TextField(blank=True, help_text='Fehler bei Sitemap-Parsing', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='sitemap_valid',
            field=models.BooleanField(blank=True, default=False, help_text='True, wenn sitemap.xml gültiges XML ist', null=True),
        ),
    ]
