# Generated by Django 4.2.21 on 2025-06-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0022_seoaudit_backlink_count_seoaudit_referring_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='domain_authority',
            field=models.FloatField(blank=True, help_text='Domain Authority (Moz)', null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='trust_score',
            field=models.FloatField(blank=True, help_text='Spam Score (Moz)', null=True),
        ),
    ]
