# Generated by Django 4.2.21 on 2025-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0024_seoaudit_anchor_text_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudit',
            name='facebook_avg_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='facebook_avg_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='facebook_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='instagram_avg_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='instagram_avg_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='instagram_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='linkedin_avg_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='linkedin_avg_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoaudit',
            name='linkedin_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
