name: Smoke Tests

on:
# Manuelles Auslösen im UI
  workflow_dispatch:
  
  schedule:
    # alle 30 Minuten
    - cron: '*/30 * * * *'

jobs:
  smoke:
    name: Smoke test Frontend & API
    runs-on: ubuntu-latest
    steps:
      - name: Health-check Frontend
        run: |
          code=$(curl -o /dev/null -s -w "%{http_code}" https://heylenny.app/)
          if [ "$code" != "200" ]; then
            echo "Frontend health returned $code"
            exit 1
          fi

      - name: Health-check API
        run: |
          code=$(curl -o /dev/null -s -w "%{http_code}" https://api.heylenny.app/api/health/)
          if [ "$code" != "200" ]; then
            echo "API health returned $code"
            exit 1
          fi
